import type { QRPreset } from "../types";

export const QR_PRESETS: QRPreset[] = [
  {
    id: "classic",
    name: "Classic Noir",
    description: "Standard high-contrast black & white with square precision",
    dotsColor: "#0F172A",
    isGradient: false,
    gradientType: "linear",
    gradientRotation: 0,
    backgroundColor: "#FFFFFF",
    dotsType: "square",
    cornersSquareType: "square",
    cornersDotType: "square",
    cornersSquareColor: "#0F172A",
    cornersDotColor: "#0F172A",
    errorCorrectionLevel: "M",
  },
  {
    id: "cyber-neon",
    name: "Cyberpunk Neon",
    description: "Vibrant violet-to-cyan gradient on deep night slate",
    dotsColor: "#8B5CF6",
    dotsColor2: "#06B6D4",
    isGradient: true,
    gradientType: "linear",
    gradientRotation: 45,
    backgroundColor: "#0A0F1D",
    dotsType: "dots",
    cornersSquareType: "extra-rounded",
    cornersDotType: "dot",
    cornersSquareColor: "#06B6D4",
    cornersDotColor: "#A855F7",
    errorCorrectionLevel: "Q",
  },
  {
    id: "emerald",
    name: "Emerald Luxe",
    description: "Rich forest jewel gradient with classy curves",
    dotsColor: "#065F46",
    dotsColor2: "#10B981",
    isGradient: true,
    gradientType: "linear",
    gradientRotation: 135,
    backgroundColor: "#F0FDF4",
    dotsType: "classy",
    cornersSquareType: "extra-rounded",
    cornersDotType: "dot",
    cornersSquareColor: "#047857",
    cornersDotColor: "#065F46",
    errorCorrectionLevel: "M",
  },
  {
    id: "sunset",
    name: "Sunset Blaze",
    description: "Vivid coral-to-amber radial warmth",
    dotsColor: "#E11D48",
    dotsColor2: "#F97316",
    isGradient: true,
    gradientType: "linear",
    gradientRotation: 90,
    backgroundColor: "#FFF7ED",
    dotsType: "rounded",
    cornersSquareType: "extra-rounded",
    cornersDotType: "dot",
    cornersSquareColor: "#E11D48",
    cornersDotColor: "#F97316",
    errorCorrectionLevel: "H",
  },
  {
    id: "royal-gold",
    name: "Royal Gold",
    description: "Opulent gilded bronze and amber on deep onyx",
    dotsColor: "#D97706",
    dotsColor2: "#F59E0B",
    isGradient: true,
    gradientType: "linear",
    gradientRotation: 45,
    backgroundColor: "#0F172A",
    dotsType: "classy-rounded",
    cornersSquareType: "extra-rounded",
    cornersDotType: "square",
    cornersSquareColor: "#F59E0B",
    cornersDotColor: "#D97706",
    errorCorrectionLevel: "H",
  },
  {
    id: "ocean-breeze",
    name: "Ocean Wave",
    description: "Cool azure and cobalt sea breeze",
    dotsColor: "#0284C7",
    dotsColor2: "#2563EB",
    isGradient: true,
    gradientType: "linear",
    gradientRotation: 120,
    backgroundColor: "#F0F9FF",
    dotsType: "rounded",
    cornersSquareType: "square",
    cornersDotType: "dot",
    cornersSquareColor: "#0284C7",
    cornersDotColor: "#2563EB",
    errorCorrectionLevel: "M",
  },
  {
    id: "midnight-stealth",
    name: "Midnight Stealth",
    description: "Sleek crisp silver on matte titanium dark mode",
    dotsColor: "#E2E8F0",
    isGradient: false,
    gradientType: "linear",
    gradientRotation: 0,
    backgroundColor: "#1E293B",
    dotsType: "extra-rounded",
    cornersSquareType: "extra-rounded",
    cornersDotType: "dot",
    cornersSquareColor: "#94A3B8",
    cornersDotColor: "#F1F5F9",
    errorCorrectionLevel: "M",
  },
  {
    id: "berry-velvet",
    name: "Berry Velvet",
    description: "Sophisticated magenta & ruby gradient on soft blush",
    dotsColor: "#9D174D",
    dotsColor2: "#DB2777",
    isGradient: true,
    gradientType: "linear",
    gradientRotation: 45,
    backgroundColor: "#FDF2F8",
    dotsType: "dots",
    cornersSquareType: "dot",
    cornersDotType: "dot",
    cornersSquareColor: "#BE185D",
    cornersDotColor: "#9D174D",
    errorCorrectionLevel: "Q",
  },
];
